Added Italian Locale
wanasit/chrono pull request #460
Opened 2022-07-04 10:48 UTC by ntotao

Added locales/it translations for Italian Language support

2022-07-09 03:35 UTC, wanasit commented
Hello @ntotao. Thanks for your contribution!! I will try to complete reviewing you change as soon as possible, but there is an obvious feedback I'd like to ask.
 
Could you also include the tests for the new locale? 

The tests are as important if not more important than the parsers. Only with the tests, we can keep the parsers work both for now and in the future. Imagine, if I or other contributors who don't speak Italian trying to refactor or making change to Chrono, we would never know if it works correctly for Italian without your tests.

2022-09-16 17:17 UTC, federicodilo commented
I can test it if needed, could you please tell me how?

2022-09-23 08:39 UTC, wanasit commented
@federicodilo Thanks for looking. Sorry for my slow reply. 

As you see, tests for different locales are not equally comprehensive. But, in general, the more tests the better. 

The tests with the highest priorities (high ROI) are probably:
* The locale general test (e.g. `en.test.ts`) with commonly used and pitfall
* If timing expression is difficult in IT, you may want to add time-specific tests (e.g. `en_time_exp.test.ts`)
* The relative time (e.g. time unit or time ago) is different from the normal date/time. We should also test those (if the locale supports relative time expression) e.g. `en_time_units_ago.test.ts`

You also do not need to copy and translate English. It is simply a good place to start, but do whatever input and expected output make sense in the locale.

2022-09-24 05:25 UTC, federicodilo requested changes

2022-09-24 05:25 UTC, federicodilo commented on src/locales/it/constants.ts
> +    } else if (num.match(/metá/)) {
metà

2022-09-24 05:25 UTC, federicodilo commented on src/locales/it/constants.ts
> +    num = num.replace(/(?:imo|ndo|rzo|rto|nto|sto|tavo|nono|cimo|timo|esimo)$/i, "");
It makes no sense since ordinal numbers in Italian are obtained by adding "°" sign (eg. 1°, 2°, 10°, 152°)

2024-05-27 15:26 UTC, vetrek commented
Hi @ntotao, any updates :) ?

2024-07-25 09:16 UTC, filippozanfini commented
Any updates on this?

2024-08-08 10:25 UTC, filippozanfini commented
Please merge this @ntotao  @wanasit  🙏

2025-03-18 15:30 UTC, filippozanfini commented
@ntotao @wanasit any update on this?

2025-03-30 12:40 UTC, merged

2025-03-30 12:44 UTC, wanasit commented
Sorry for my slow reply. 

I was waiting for the PR owner to revise the change (esp. testing).
However, the change seems already useful to some of the requesters.
So, I will include this in the next patch.

Remember, the IT locale support is totally untested, and I don't speak Italian.

2025-04-19 08:57 UTC, filippozanfini commented
@wanasit I don't see the import of the Italian language
<img width="1008" alt="Screenshot 2025-04-19 alle 10 56 57" src="https://github.com/user-attachments/assets/b2c4482b-d518-4c44-a57a-1482979a8b4c" />